#!/usr/bin/env bash
set -euo pipefail

# Generate a DEVELOPMENT/TEST signing keystore for release-variant APK builds.
#
# This script is NOT used by automated production release pipelines. It exists
# so a developer can locally produce a signed release-variant APK for testing
# the release code path, without needing access to the production key. For a
# real release:
#   * Either drop the production keystore into app/keystore.properties yourself
#     (DO NOT commit that file), or
#   * Provide the SSR_KEYSTORE_* environment variables in CI.
#
# The script writes two gitignored artefacts:
#   1. app/keystore/studyshot.keystore   (the keystore, gitignored)
#   2. app/keystore.properties           (parsed by app/build.gradle.kts, gitignored)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
STORE_DIR="${PROJECT_DIR}/app/keystore"
STORE_FILE="${STORE_DIR}/studyshot.keystore"
PROPS_FILE="${PROJECT_DIR}/app/keystore.properties"
STORE_PASS="studyshot"
KEY_ALIAS="studyshot"
KEY_PASS="studyshot"

mkdir -p "$STORE_DIR"

if [[ -f "$STORE_FILE" ]]; then
  echo "Keystore already exists: $STORE_FILE"
  if [[ ! -f "$PROPS_FILE" ]]; then
    cat > "$PROPS_FILE" <<EOF
# DEVELOPMENT keystore — generated by scripts/generate-keystore.sh.
# Do NOT commit. Replace with production keystore for real releases.
storeFile=app/keystore/studyshot.keystore
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASS
EOF
    echo "Wrote $PROPS_FILE"
  fi
  exit 0
fi

keytool -genkey \
  -v \
  -keystore "$STORE_FILE" \
  -alias "$KEY_ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -storepass "$STORE_PASS" \
  -keypass "$KEY_PASS" \
  -dname "CN=StudyShot Relay, OU=StudyShot, O=StudyShot, L=Unknown, ST=Unknown, C=CN"

cat > "$PROPS_FILE" <<EOF
# DEVELOPMENT keystore — generated by scripts/generate-keystore.sh.
# Do NOT commit. Replace with production keystore for real releases.
storeFile=app/keystore/studyshot.keystore
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASS
EOF

echo "Generated DEVELOPMENT keystore: $STORE_FILE"
echo "Wrote $PROPS_FILE"
echo "WARNING: This is a development/test keystore. Do not use it for production releases."
