package com.studyshot.relay.ui.management

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material.icons.outlined.PhoneAndroid
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.studyshot.relay.ui.components.HelpCallout
import com.studyshot.relay.ui.components.SectionHeader
import com.studyshot.relay.ui.components.SettingsGroup
import com.studyshot.relay.ui.components.SettingsRow
import com.studyshot.relay.ui.components.SurfaceCard
import com.studyshot.relay.ui.navigation.AppState
import com.studyshot.relay.ui.navigation.StatusTone
import com.studyshot.relay.ui.navigation.TransientMessage
import com.studyshot.relay.ui.theme.Teal600

@Composable
fun ManagementCreateCodeScreen(
    state: AppState,
) {
    val settings by state.app.secureSettings.settings.collectAsState()
    val generated by state.generatedBindCode.collectAsState()
    val clipboard = LocalClipboardManager.current
    var hint by rememberSaveable(settings.deviceName) { mutableStateOf(settings.deviceName) }
    var creating by remember { mutableStateOf(false) }

    LaunchedEffect(generated?.bindCode) {
        val code = generated?.bindCode ?: return@LaunchedEffect
        clipboard.setText(AnnotatedString(code))
        state.emit(TransientMessage("绑定码已生成并复制到剪贴板", StatusTone.Positive))
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(bottom = 32.dp),
    ) {
        SectionHeader(
            title = "创建绑定码",
            subtitle = "把绑定码告诉要加入的设备。在新设备上打开 StudyShot Relay → 绑定到服务器。",
        )
        HelpCallout(
            text = "绑定码一次性使用，过期时间由服务器配置决定。",
            modifier = Modifier.padding(horizontal = 16.dp, vertical = 4.dp),
        )
        Spacer(Modifier.height(8.dp))
        SettingsGroup(
            title = "设备名提示",
            footer = "仅用于让你自己记得这个绑定码是给哪个设备准备的；不影响实际注册。",
        ) {
            SettingsRow(
                icon = Icons.Outlined.PhoneAndroid,
                title = "设备名提示",
                value = hint,
                isLast = false,
            )
            OutlinedTextField(
                value = hint,
                onValueChange = { hint = it },
                singleLine = true,
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 14.dp, vertical = 4.dp),
                placeholder = { Text("如：客厅 iPad") },
            )
        }
        Spacer(Modifier.height(16.dp))

        if (generated != null) {
            SurfaceCard(
                modifier = Modifier.padding(horizontal = 16.dp),
                contentPadding = androidx.compose.foundation.layout.PaddingValues(16.dp),
            ) {
                Text(
                    text = "当前绑定码",
                    style = MaterialTheme.typography.labelLarge,
                )
                Spacer(Modifier.height(8.dp))
                SelectionContainer {
                    Text(
                        text = generated?.bindCode.orEmpty(),
                        style = MaterialTheme.typography.headlineMedium,
                        fontWeight = FontWeight.Bold,
                        color = Teal600,
                    )
                }
                Spacer(Modifier.height(4.dp))
                Text(
                    text = "有效期至 ${generated?.expiresAt.orEmpty()}。离开页面后仍会保留到退出管理。",
                    style = MaterialTheme.typography.bodySmall,
                )
                Spacer(Modifier.height(10.dp))
                OutlinedButton(
                    onClick = {
                        clipboard.setText(AnnotatedString(generated?.bindCode.orEmpty()))
                        state.emit(TransientMessage("绑定码已复制", StatusTone.Positive))
                    },
                ) {
                    Icon(
                        imageVector = Icons.Outlined.ContentCopy,
                        contentDescription = null,
                    )
                    Spacer(Modifier.size(6.dp))
                    Text("复制绑定码")
                }
            }
            Spacer(Modifier.height(16.dp))
        }

        Button(
            onClick = {
                creating = true
                state.createBindCode(hint, onComplete = { creating = false })
            },
            enabled = !creating,
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 16.dp),
            colors = ButtonDefaults.buttonColors(
                containerColor = Teal600,
                contentColor = androidx.compose.ui.graphics.Color.White,
            ),
        ) {
            Text(
                text = if (creating) "生成中…" else "生成绑定码",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.SemiBold,
            )
        }
    }
}
